apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: airflow
    tier: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
---
apiVersion: v1
kind: Service
metadata:
  name: flower
spec:
  type: NodePort
  selector:
    app: airflow
    tier: flower
  ports:
    - port: 5555
      targetPort: 5555
      nodePort: 32081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: db
  template:
    metadata:
      labels:
        app: airflow
        tier: db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_DB
              value: airflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: rabbitmq
  template:
    metadata:
      labels:
        app: airflow
        tier: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: airflow
            - name: RABBITMQ_DEFAULT_PASS
              value: airflow
            - name: RABBITMQ_DEFAULT_VHOST
              value: airflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: web
  template:
    metadata:
      labels:
        app: airflow
        tier: web
    spec:
      initContainers:
        - name: init-airflow-db
          image: apache/airflow:2.8.1
          command: ["sh", "-c"]
          args:
            - airflow db migrate && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      containers:
        - name: web
          image: apache/airflow:2.8.1
          args: ["webserver"]
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: scheduler
  template:
    metadata:
      labels:
        app: airflow
        tier: scheduler
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:2.8.1
          args: ["scheduler"]
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: worker
  template:
    metadata:
      labels:
        app: airflow
        tier: worker
    spec:
      containers:
        - name: worker
          image: apache/airflow:2.8.1
          args: ["celery", "worker"]
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: flower
  template:
    metadata:
      labels:
        app: airflow
        tier: flower
    spec:
      containers:
        - name: flower
          image: apache/airflow:2.8.1
          command: ["airflow", "celery", "flower"]
          env:
            - name: AIRFLOW__CELERY__BROKER_URL
              value: amqp://airflow:airflow@rabbitmq:5672/airflow
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor
          ports:
            - containerPort: 5555